### ISSUE TITLE
Installation instruction doesn't work on Ubuntu 14.04

### ISSUE THREAD

**Issue by quasiyoke** [librevault/librevault.com#2]
This command:

``` sh
echo deb https://releases.librevault.com/debian/ $(lsb_release -cs)/ | sudo tee /etc/apt/sources.list.d/librevault.list
```

...produces such `librevault.list` on Ubuntu 14.04:

```
deb https://releases.librevault.com/debian/ trusty/
```

...which results in 404 during `apt update` of course.

**Comment by GamePad64** [comment]
https://librevault.com/download/ states clearly, that only 15.10 and 16.04 are supported.
14.04 has very old libstdc++ (so, I have to link it statically) and Qt, which I cannot link statically, because of Qt WebKit (and I will ship dynamically linked Qt in the new releases for Windows).
I had an experimental build, where all the application and libraries were placed in `/opt`, but it was very ugly and barely supportable.

**Comment by songsen** [comment]
...produces such librevault.list on Ubuntu 16.04:
deb https://releases.librevault.com/debian xenial  main
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7ECABE6D2866013E2D9DB819F6CDDCEF4B158906

...but the results : 
executing: /tmp/tmp.WtEjAAPJXN/gpg.1.sh --keyserver
keyserver.ubuntu.com
--recv-keys
7ECABE6D2866013E2D9DB819F6CDDCEF4B158906
gpg: requesting key 4B158906 from hkp server keyserver.ubuntu.com
?: keyserver.ubuntu.com: Connection refused
gpgkeys: HTTP fetch error 7: couldn't connect: Connection refused
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver unreachable
gpg: keyserver communications error: public key not found
gpg: keyserver receive failed: public key not found
